<?php

if ( function_exists( 'acf_add_options_page' ) ):

	acf_add_options_page( array(
		'page_title'      => __( 'Options', 'understrap-child' ),
		'menu_title'      => __( 'Theme options', 'understrap-child' ),
		'menu_slug'       => 'theme_options',
		'capability'      => 'edit_posts',
		'position'        => '',
		'parent_slug'     => '',
		'icon_url'        => '',
		'redirect'        => true,
		'post_id'         => 'theme_options',
		'autoload'        => true,
		'update_button'   => __( 'Save', 'understrap-child' ),
		'updated_message' => __( 'Options Saved', 'understrap-child' ),
	) );

endif;

if ( function_exists( 'acf_add_local_field_group' ) ):

	acf_add_local_field_group( array(
		'key'                   => 'group_5f91698b4d14d',
		'title'                 => __( 'Options', 'understrap-child' ),
		'fields'                => array(
			array(
				'key'               => 'field_5f916e1a75171',
				'label'             => __( 'Header', 'understrap-child' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5f916e3475172',
				'label'             => __( 'Logo', 'understrap-child' ),
				'name'              => 'logo',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'preview_size'      => 'full',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5f9169a1bef1e',
				'label'             => __( 'Tweaks', 'understrap-child' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'acfe_permissions'  => array(
					0 => 'administrator',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5f9169cfbef1f',
				'label'             => __( 'Show admin bar', 'understrap-child' ),
				'name'              => 'show_admin_bar',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'acfe_permissions'  => array(
					0 => 'administrator',
				),
				'message'           => '',
				'default_value'     => 1,
				'ui'                => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
			array(
				'key'               => 'field_5f9da36e11e5a',
				'label'             => __( 'Posts', 'understrap-child' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5f9da3b311e5b',
				'label'             => __( 'Default featured image', 'understrap-child' ),
				'name'              => 'default_image',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5f9ed7c7545fb',
				'label'             => __( 'Default page banner', 'understrap-child' ),
				'name'              => 'page_banner',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5fa3f3eeac657',
				'label'             => __( 'Blog page default image', 'understrap-child' ),
				'name'              => 'blog_default_image',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5fa131be52120',
				'label'             => __( 'Contacts', 'understrap-child' ),
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'left',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5fa15091c9e86',
				'label'             => __( 'Address', 'understrap-child' ),
				'name'              => 'address',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5fa131d452121',
				'label'             => __( 'Phone', 'understrap-child' ),
				'name'              => 'phone',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
			array(
				'key'               => 'field_5fa1320652122',
				'label'             => __( 'Email', 'understrap-child' ),
				'name'              => 'email',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'theme_options',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5f91ae01abeec',
		'title'                 => __( 'Menu logo', 'understrap-child' ),
		'fields'                => array(
			array(
				'key'               => 'field_5f91ae2205654',
				'label'             => __( 'Show logo', 'understrap-child' ),
				'name'              => 'show_logo',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'ui'                => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'nav_menu_item',
					'operator' => '==',
					'value'    => 'location/primary',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5f9ed8c825222',
		'title'                 => __( 'Posts options', 'understrap-child' ),
		'fields'                => array(
			array(
				'key'               => 'field_5f9ed8ebaf453',
				'label'             => __( 'Post banner', 'understrap-child' ),
				'name'              => 'post_banner',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'preview_size'      => 'medium',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5f9ee9fa8e3ea',
				'label'             => __( 'Custom content', 'understrap-child' ),
				'name'              => 'custom_content',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'ui'                => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
			array(
				'key'                  => 'field_5f9eefbc8e3eb',
				'label'                => __( 'Banner content', 'understrap-child' ),
				'name'                 => 'banner_content',
				'type'                 => 'visual_composer',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => array(
					array(
						array(
							'field'    => 'field_5f9ee9fa8e3ea',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'view_mode'            => 'compact',
				'allow_classic_mode'   => 0,
				'edit_btn_label'       => __( 'Edit content', 'understrap-child' ),
				'done_btn_label'       => __( 'Done', 'understrap-child' ),
				'fullscreen_btn_label' => __( 'Full screen mode', 'understrap-child' ),
				'description_label'    => __( 'Description', 'understrap-child' ),
				'return_format'        => 'complete',
				'front_wrapper'        => array(
					'id'    => '',
					'class' => '',
					'style' => '',
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'post',
				),
			),
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5fa297be60970',
		'title'                 => __( 'Blog content', 'understrap-child' ),
		'fields'                => array(
			array(
				'key'                  => 'field_5fa297e64fb88',
				'label'                => __( '', 'understrap-child' ),
				'name'                 => 'blog_content',
				'type'                 => 'visual_composer',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'view_mode'            => 'compact',
				'allow_classic_mode'   => 0,
				'edit_btn_label'       => __( 'Edit content', 'understrap-child' ),
				'done_btn_label'       => __( 'Done', 'understrap-child' ),
				'fullscreen_btn_label' => __( 'Full screen mode', 'understrap-child' ),
				'description_label'    => __( 'Description', 'understrap-child' ),
				'return_format'        => 'complete',
				'front_wrapper'        => array(
					'id'    => '',
					'class' => '',
					'style' => '',
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'page_type',
					'operator' => '==',
					'value'    => 'posts_page',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

	acf_add_local_field_group( array(
		'key'                   => 'group_5fad5da745510',
		'title'                 => __( 'Hide featured image', 'understrap-child' ),
		'fields'                => array(
			array(
				'key'               => 'field_5fad5dbe22e04',
				'label'             => __( 'Hide featured image on the page of post', 'understrap-child' ),
				'name'              => 'hide_featured_image',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 0,
				'ui'                => 0,
				'ui_on_text'        => '',
				'ui_off_text'       => '',
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'post',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
	) );

endif;
